import dynamic from "next/dynamic";
import Address from "../components/Address";
import Category from "../components/Category";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Kitchen from "../components/Kitchen";

export const metadata = {
  title: 'Anasayfa',
  description: 'Generated by create next app',
}

const NoSSR = dynamic(() => import('../components/HeroSection'), { ssr: false })


export default function Home() {
  return (
    
    <main>
      <Header/>
      <NoSSR/>
      <Address/>
      <Kitchen/>
      <Category/>
      <Footer/>
    </main>
    

  )
}
