import Address from "../components/Address";
import Category from "../components/Category";
import Footer from "../components/Footer";
import Header from "../components/Header";
import HeroSection from "../components/HeroSection";
import Kitchen from "../components/Kitchen";

export const metadata = {
  title: 'Anasayfa',
  description: 'Generated by create next app',
}



export default function Home() {
  return (
    <main>
      <Header/>
      <HeroSection/>
      <Address/>
      <Kitchen/>
      <Category/>
      <Footer/>
    </main>

  )
}
